name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

# Ensure this only runs on tag creation, not branch pushes
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Tag Trigger
        run: |
          echo "This workflow should only run on tag pushes"
          echo "Current ref: ${{ github.ref }}"
          echo "Current ref_name: ${{ github.ref_name }}"
          echo "Current event_name: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" != "push" ]]; then
            echo "Error: This workflow should only run on push events"
            exit 1
          fi
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            echo "Error: This workflow should only run on version tags (v*.*.*)"
            exit 1
          fi
          echo "✅ Valid tag trigger confirmed"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Build Electron App
        run: npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Portable
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: dist-v2.2.0b/*.exe
          retention-days: 30

  create-release:
    needs: build
    runs-on: ubuntu-latest
    # Only run if this was triggered by a tag push
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Release Trigger
        run: |
          echo "Creating release for tag: ${{ github.ref_name }}"
          echo "Tag ref: ${{ github.ref }}"
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            echo "Error: This should only run on version tags"
            exit 1
          fi
          echo "✅ Valid release trigger confirmed"

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          generateReleaseNotes: true
          artifacts: |
            ./artifacts/windows-portable/*
          token: ${{ secrets.GITHUB_TOKEN }}
